Fixed node/npm detection

diff --git a/ui/bin/build-appsuite b/ui/bin/build-appsuite
--- a/ui/bin/build-appsuite
+++ b/ui/bin/build-appsuite
@@ -1,11 +1,23 @@
 #!/bin/sh
 
+if [ -z $NODEJS ]
+then
+    if command -v nodejs > /dev/null; then NODEJS=nodejs; else NODEJS=node; fi
+fi
+
 export BASEDIR="$(dirname "$(dirname "$(readlink "$0" || echo "$0")")")"
-export NPMBINDIR="$(npm -g bin)"
+
+[ -f local.conf ] && . ./local.conf
+
+if command -v $NODEJS > /dev/null; then
+    export NPMBINDIR="$($(dirname $NODEJS)/npm -g bin)"
+else
+    echo "node binary not found in path. You need to install node and have it in your path."
+    exit 1
+fi
 
 if [ -f $NPMBINDIR/grunt ];
 then
-    [ -f local.conf ] && . ./local.conf
     $NPMBINDIR/grunt "$@"
 else
     echo "grunt binary not found in path. Consider installing it with 'npm install -g grunt-cli'"
