switch to grunt in build-appsuite script

diff --git a/ui/bin/build-appsuite b/ui/bin/build-appsuite
--- a/ui/bin/build-appsuite
+++ b/ui/bin/build-appsuite
@@ -1,18 +1,9 @@
 #!/bin/sh
 
-if [ ! -d apps ]
-then
-    echo No apps directory found. Are you in the correct directory? >&2
-    exit 1
-fi
-
-if [ -z $NODEJS ]
-then
-    if command -v nodejs > /dev/null; then NODEJS=nodejs; else NODEJS=node; fi
-fi
-
 export BASEDIR="$(dirname "$(dirname "$(readlink "$0" || echo "$0")")")"
+
+which grunt >/dev/null || (echo "grunt binary not found in path. Consider installing it with 'npm install -g grunt-cli'" && exit 1)
 
 [ -f local.conf ] && . ./local.conf
 
-$NODEJS $nodeopts "$BASEDIR/lib/jake/bin/cli.js" -f "$BASEDIR/Jakefile" "$@"
+grunt "$@"
